# Generated by Django 4.1.7 on 2023-02-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishchilar',
            name='worker_brithday',
        ),
        migrations.RemoveField(
            model_name='ishchilar',
            name='worker_location',
        ),
        migrations.AlterField(
            model_name='ishchilar',
            name='worker_age',
            field=models.IntegerField(verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='ishchilar',
            name='worker_name',
            field=models.CharField(max_length=45, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='ishchilar',
            name='worker_surname',
            field=models.CharField(max_length=45, verbose_name='Familiya'),
        ),
    ]
